routes/api.py
from concurrent.futures import ThreadPoolExecutor
import json
from flask import (
    Blueprint,
    jsonify,
    redirect,
    request,
    session,
    url_for,
    send_file,
)

# from flask_login import login_user, logout_user, login_required

from models.Logger import logger
from models.RedditCredentials import RedditCredentials
from models.Video import Video
from models.User import User
from utils.util import login_required



# API ==========================================================================
api = Blueprint("api", __name__)


# 
@api.route('/keys', methods=['POST'])
@login_required
def api_keys():
    logger.info("Adding API Keys =====================================")
    # Create a RedditCredentials object
    try:
        redditCredential = RedditCredentials(
            client_id = request.form['client_id'],
            client_secret = request.form['client_secret'],
            user_agent = request.form['user_agent'],
            username = request.form['user_agent'],
            password = request.form['password'],
            twofa= "false"
        )
        ytdataapicerdentials = request.form['ytdata']
        # secret = from_ytdata(ytdataapicerdentials)
        
        print(redditCredential)
        # Save the credentials to a file
        # redditCredential.save_to_file(".env")
        

        
        # secret.save_to_file("client_secrets.json")
        with open("client_secrets.json", 'w') as f:
            json.dump(ytdataapicerdentials, f)
            
        # redditCredential.save_to_file(".env")
        with open(".env", "w") as file:
            file.write(f"client_id=\"{redditCredential.client_id}\"\n")
            file.write(f"client_secret=\"{redditCredential.client_secret}\"\n")
            file.write(f"username=\"{redditCredential.username}\"\n")
            file.write(f"user_agent=\"{redditCredential.user_agent}\"\n")
            file.write(f"password=\"{redditCredential.password}\"\n")
            file.write(f"2fa=\"{redditCredential.twofa}\"")

        logger.info("Keys Added =====================================")
        return redirect(url_for("view.secrets"))
    except Exception as e:
        logger.error("Error in adding keys =====================================")
        return redirect(url_for("view.addkeys", error=str(e)))


# DONE
@api.route('/video', methods=['GET'])
@login_required
def api_video():
    logger.info("All Videos =====================================")
    data = User.get_all_videos(session["username"])
    # return redirect(url_for("view.videos"),Response=jsonify(data))
    return jsonify(data)

# DONE
@api.route('/video', methods=['POST'])
@login_required
def api_create_video():
    toyt = request.form.get('toyt')
    toup = False
    if toyt == "on":
        toup = True
    
    logger.critical(f"toyt ==========UPLOADTOYT======== {toyt}")
    print("Creating Video =====================================")
    subreddit = request.form.get('subreddit') or "memes"
    logger.info("API Create Video With Input ============================")
    executor = ThreadPoolExecutor()
    executor.submit(User.make_new_video, session['username'], subreddit, toup)
    successMSG = "Video is being created"    
    return redirect(url_for("view.index", success=successMSG))

# DONE
@api.route('/video/<videoid>', methods=['GET'])
def api_get_video(videoid):
    logger.info("Getting Video MP4 =====================================")
    video_path = f'Users/{session["username"]}/{videoid}.mp4'
    return send_file(video_path, mimetype='video/mp4')


# DONE
@api.route('/upload/<video_id>')
@login_required
def api_upload_video(video_id):
    logger.info("Uploading Video =====================================")
    executor = ThreadPoolExecutor()
    executor.submit(User.upload_the_video,video_id,session['username'])
    successMsg = "Video is being uploaded"
    return redirect(url_for("view.videos", success=successMsg))

# DONE
@api.route('/update/<video_id>', methods=['POST'])
@login_required
def api_update_video(video_id):
    logger.info("Updating Video =====================================")
    newVideo = Video(
        title = request.form['title'],
        description = request.form['description'],
        keywords = request.form['keywords'],
        privacyStatus = request.form['privacyStatus'],
        videoid=video_id
    )
    User.update_the_video(newVideo,session['username'])
    return redirect(url_for("view.videos"))

# DONE
@api.route('/delete/<video_id>')
@login_required
def api_delete_video(video_id):
    logger.info("Deleting Video =====================================")
    executor = ThreadPoolExecutor()
    executor.submit(User.delete_the_video, video_id, session['username'])
    return redirect(url_for("view.videos", success="Video is being deleted"))

routes/view.py
import json
import os

from flask import (
    Blueprint,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from models.Logger import logger
from models.RedditCredentials import RedditCredentials
from models.Video import Video
from models.User import User
from utils.util import (
    already_logged_in,
    login_required,
)



# DONE
# VIEW ==========================================================================
view = Blueprint("view", __name__)


# DONE
@view.route('/')
@login_required
def index():
    errorMSG = request.args.get('error')
    successMSG = request.args.get('success')
    with open("markdown/guid.md", "r") as file:
        mkdown = file.read()
    
    logger.info("=================Index===========================")
    # senf markdown to template
    return render_template('index.html', mkdown=mkdown, error=errorMSG, success=successMSG)

# DONE
@view.route('/index')
@login_required
def toindex():
    logger.info("=================To Index===========================")
    errorMSG = request.args.get('error')
    successMSG = request.args.get('success')
    return redirect(url_for("index"), error=errorMSG, success=successMSG)
    
# 
@view.route('/secrets')
@login_required
def secrets():    
    try:
        rCred = RedditCredentials()
        # print(rCred)
        rCred.update_from_env()
        with open('client_secrets.json', 'r') as f:
            ytdataapicredentials = json.load(f)
        # print(ytdataapicredentials["installed"]["client_id"])
        logger.info("=================Secrets===========================")
        
        return render_template('secrets.html',
                                redditdata = rCred,
                                ytdata=ytdataapicredentials
                                )
    except:
        error = "Error in secrets"
        # flash(error, 'error')
        logger.error("Error in secrets========================")
        return redirect(url_for("view.addkeys"))
    

@view.route('/addkeys')
@login_required
def addkeys():
    rCred = RedditCredentials(
        client_id = os.getenv("client_id"),
        client_secret = os.getenv("client_secret"),
        username = os.getenv("username"),
        user_agent = os.getenv("user_agent"),
        password = os.getenv("password"),
        twofa= os.getenv("2fa") == "true"
    )
    
    with open("markdown/addkeys.md", "r") as file:
        mkdown = file.read()

    
    try:
        rCred.update_from_env()
        
        with open('client_secrets.json', 'r') as f:
            ytdataapicredentials = json.load(f)

        error = request.args.get('error')
        logger.info("=================Add Keys===========================")
        return render_template('addkeys.html', error=error, redditdata = rCred, ytdata=ytdataapicredentials, mkdown=mkdown)
    except:
        return render_template('addkeys.html', error="Error in addkeys", redditdata = rCred, ytdata=None, mkdown=mkdown)

# DONE
@view.route('/makevideo')
@login_required
def make_video():
    with open("markdown/newvideo.md", "r") as file:
        newvideomd = file.read()
    logger.info("=================Make Video===========================")
    return render_template('makevideo.html',newvideomd=newvideomd)


# DONE
@view.route('/updatevideo/<video_id>')
@login_required
def update_video(video_id):
    logger.info(f"=================Update Video {video_id}===========================")
    videoData= User.get_video(video_id, session["username"])
    return render_template('updatevideo.html',video_data = videoData.to_dict())


# DONE
@view.route('/videos')
@login_required
def videos():
    errorMSG = request.args.get('error')
    successMSG = request.args.get('success')
    logger.info("=================Videos===========================")
    # video_data = User.get_all_videos(session["username"])
    path = os.path.join("Users",session["username"])
    path = os.path.join(path,"videos.json")
    video_data = Video.get_all_videos(filename = path)
    # print(video_data[0].to_dict())
    return render_template('videos.html',video_data = video_data,error=errorMSG,success=successMSG)

@view.route('/video/<video_id>')
@login_required
def video(video_id):
    logger.info(f"=================See Video {video_id}===========================")
    videoData = User.get_video(video_id, session["username"])
    if videoData is None:
        errorMSG = 'this video does not exist : 404 error'
        return render_template('404.html',error=errorMSG), 404
    return render_template('video.html',video_data= videoData.to_dict() ,path = f"api/video/{video_id}")

# DONE
@view.route('/login')
@already_logged_in
def login():
    errorMSG = request.args.get('error')
    logger.info("=================Login===========================")
    return render_template('login.html', error=errorMSG)

# DONE
@view.route('/signup')
@already_logged_in
def signup():
    errorMSG = request.args.get('error')
    logger.info("=================Signup===========================")
    return render_template('signup.html', error=errorMSG)

templates/addkeys.html
{% extends "layout.html" %}

{% block title %}Reddit & YT Credentials{% endblock %}

{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}


{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <h1>
            Credential Keys
        </h1>
        <h4>Enter your Reddit API keys</h4>
        <form method="POST" action="/api/keys">
            <div class="form-group">
                <label for="client_id">Client ID</label>
                <input type="text" class="form-control" id="client_id" name="client_id"
                    placeholder="{{redditdata.client_id}}">
            </div>
            <div class="form-group">
                <label for="client_secret">Client Secret</label>
                <input type="text" class="form-control" id="client_secret" name="client_secret"
                    placeholder="{{redditdata.client_secret}}">
            </div>
            <!-- <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div> -->
            <div class="form-group">
                <label for="user_agent">User Agent</label>
                <input type="text" class="form-control" id="user_agent" name="user_agent"
                    placeholder="{{redditdata.user_agent}}">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password"
                    placeholder="{{redditdata.password}}">
            </div>
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="2fa" name="2fa">
                <label class="form-check-label" for="2fa">2FA Enabled</label>
            </div>
            <div class="form-group">
                <label for="ytdata">
                    <h4>Paste YouTube Data API v3 key Here</h4>
                </label>
                {% if ytdata %}
                <textarea class="form-control" id="ytdata" name="ytdata" placeholder="{{ytdata}}"></textarea>
                {% else %}
                <textarea class="form-control" id="ytdata" name="ytdata" placeholder="Paste your key here"></textarea>
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary mt-3">Submit</button>
        </form>

        <br><br>

        {{mkdown|markdown}}

    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block title %}RedditReels{% endblock %}

{% block content %}

{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}

{% if success %}
<div class="alert alert-success">{{ success }}</div>
{% endif %}


<!-- get markdown -->
{{ mkdown|markdown }}

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">RedditReels</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">

                    {% if 'username' in session: %}
                    <li class="nav-item rounded-pill">
                        <a class="nav-link badge-info" href="">
                            <strong>
                                {{ session['username'] }}</a>
                        </strong>
                    </li>
                    {% endif %}
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/makevideo">New Video</a>
                    </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="/addkeys">Add Keys</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link" href="/secrets">API keys</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/videos">All Videos</a>
                    </li>
                    {% if 'username' in session: %}
                    <li class="nav-item">
                        <a class="btn btn-danger" href="/auth/logout">LogOut</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-primary" href="/login">LogIn</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </nav>

        <div class="container mt-5">
            {% block content %}


            {% endblock %}
        </div>

        <!-- Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
        <script>
            // Get the current URL path
            var currentPath = window.location.pathname;

            // Select all the nav links
            var navLinks = document.querySelectorAll('.nav-link');

            // Loop through the nav links and check if their href matches the current path
            for (var i = 0; i < navLinks.length; i++) {
                var href = navLinks[i].getAttribute('href');

                if (href === currentPath) {
                    // Add the active class to the nav item
                    navLinks[i].parentElement.classList.add('active');
                } else {
                    // Remove the active class from the nav item
                    navLinks[i].parentElement.classList.remove('active');
                }
            }
        </script>

    </body>

</html>

templates/login.html
{% extends 'layout.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}

<section class="">
    <div class="px-4 py-5 px-md-5 text-center text-lg-start" style="background-color: hsl(0, 0%, 96%)">

        <div class="container-fluid h-custom">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-md-9 col-lg-6 col-xl-5">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                        class="img-fluid" alt="Sample image">
                </div>
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="card">
                        <div class="card-body py-5 px-md-5">
                            <form action="/auth/login" method="POST">
                                <!-- Username input -->
                                <div class="form-outline mb-4">
                                    <label class="form-label" for="username">Username</label>
                                    <input type="text" id="username" class="form-control form-control-lg"
                                        placeholder="Enter your username" name="username" />
                                </div>

                                <!-- Password input -->
                                <div class="form-outline mb-3">
                                    <label class="form-label" for="password">Password</label>
                                    <input type="password" id="password" class="form-control form-control-lg"
                                        placeholder="Enter password" name="password" />
                                </div>

                                <div class="d-flex justify-content-between align-items-center">
                                    <!-- Checkbox -->
                                    <div class="form-check mb-0">
                                        <input class="form-check-input me-2" type="checkbox" value=""
                                            id="form2Example3" />
                                        <label class="form-check-label" for="form2Example3">
                                            Remember me
                                        </label>
                                    </div>
                                    <a href="#!" class="text-body">Forgot password?</a>
                                </div>

                                <div class="text-center text-lg-start mt-4 pt-2">
                                    <button type="submit" class="btn btn-primary btn-lg"
                                        style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
                                    <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="/signup"
                                            class="link-danger">Register</a></p>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/makevideo.html
{% extends "layout.html" %}

{% block subreddit %}
Make New Video
{% endblock %}

{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}


{% block content %}

<div class="container mt-5">
    <h1>Subreddit Name</h1>
    <form method="POST" action="/api/video">
        <div class="form-group">
            <label for="subreddit">Subreddit</label>
            <input type="text" class="form-control" id="subreddit" name="subreddit" placeholder="memes">
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="toyt" name="toyt">
            <label class="form-check-label" for="toyt">Automatically Upload To YouTube</label>
        </div>

        <button type="submit" class="btn btn-primary mt-3">Create Video</button>
    </form>
    <br><br>
    {{ newvideomd|markdown }}


</div>
{% endblock %}

templates/profile.html
{% extends 'layout.html' %}
{% block title %}RedditReels{% endblock %}

{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}


{% block content %}



{% endblock %}

templates/secrets.html
{% extends 'layout.html' %}
{% block title %}RedditReels{% endblock %}

{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}


{% block content %}

<div class="container mt-5">
    <h1 class="text-center">Welcome to My App</h1>
    <br>
    <h2>Here are Your Secret Credentials for Reddit &amp; YouTube APIs</h2>
    <div class="container mt-4">
        <table class="table table-striped">
            <tbody>
                <tr>
                    <td>Reddit Client ID</td>
                    <td>{{ redditdata.client_id }}</td>
                </tr>
                <tr>
                    <td>Reddit Client Secret</td>
                    <td>{{ redditdata.client_secret }}</td>
                </tr>
                <tr>
                    <td>Reddit User Agent</td>
                    <td>{{ redditdata.user_agent }}</td>
                </tr>
                <tr>
                    <td>Reddit Password</td>
                    <td>{{ redditdata.password }}</td>
                </tr>
                <tr>
                    <td>Reddit 2FA</td>
                    <td>{{ "Enabled" if redditdata.two_factor_enabled else "Disabled" }}</td>
                </tr>
                <tr>
                    <td>YouTube API Key</td>
                    <td>{{ ytdata }}</td>
                </tr>
            </tbody>
        </table>
        <!-- a button to Edit API keys -->
        <a href="/addkeys" class="btn btn-primary">Edit API Keys</a>
    </div>
</div>
{% endblock %}

templates/signup.html
{% extends 'layout.html' %}
{% block title %}SignUp{% endblock %}

{% block content %}
<h2>SignUp</h2>
{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}

<section class="">
  <div class="px-4 py-5 px-md-5 text-center text-lg-start" style="background-color: hsl(0, 0%, 96%)">

    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid"
            alt="Sample image">
        </div>
        <div class="col-lg-6 mb-5 mb-lg-0">
          <div class="card">
            <div class="card-body py-5 px-md-5">
              <form action="/auth/signup" method="POST">
                <!-- Username input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="username">Username</label>
                  <input type="text" id="username" class="form-control form-control-lg"
                    placeholder="Enter your username" name="username" />
                </div>

                <!-- Email input -->
                <div class="form-outline mb-4">
                  <label class="form-label" for="email">Email address</label>
                  <input type="email" id="email" class="form-control form-control-lg"
                    placeholder="Enter a valid email address" name="email" />
                </div>

                <!-- Password input -->
                <div class="form-outline mb-3">
                  <label class="form-label" for="password">Password</label>
                  <input type="password" id="password" class="form-control form-control-lg" placeholder="Enter password"
                    name="password" />
                </div>

                <!-- Confirm password input -->
                <!-- <div class="form-outline mb-3">
                  <label class="form-label" for="password2">Confirm password</label>
                  <input type="password" id="password2" class="form-control form-control-lg"
                      placeholder="Confirm password" name="password2" />
              </div> -->


                <div class="text-center text-lg-start mt-4 pt-2">
                  <button type="submit" class="btn btn-primary btn-lg"
                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Sign Up</button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">Already have an account? <a href="/login"
                      class="link-danger">Log in</a></p>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/updatevideo.html
{% extends "layout.html" %}

{% block title %}
Update Video
{% endblock %}

{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}


{% block content %}
<div class="container mt-5">
    <h1>Video Details</h1>
    <form method="POST" action="/api/update/{{video_data.videoid}}">
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="{{video_data['title']}}">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description" rows="3"
                placeholder="{{video_data['description']}}"></textarea>
        </div>
        <!-- <div class="form-group">
            <label for="file">Video File</label>
            <input type="file" class="form-control-file" id="file" name="file" accept="video/*" required>
        </div> -->
        <div class="form-group">
            <label for="keywords">Keywords (comma separated)</label>
            <input type="text" class="form-control" id="keywords" name="keywords"
                placeholder="{{video_data['keywords']}}">
        </div>
        <div class="form-group">
            <label for="privacyStatus">Privacy Status</label>
            <select class="form-control" id="privacyStatus" name="privacyStatus">
                <option value="private">Private</option>
                <option value="unlisted">Unlisted</option>
                <option value="public">Public</option>
            </select>
            <p class="alert-danger mt-1">YouTube API will not let you upload to public !!!</p>
        </div>
        <button type="submit" class="btn btn-primary mt-3">Update Video Details</button>
    </form>
</div>
{% endblock %}

templates/video.html
{% extends "layout.html" %}

{% block content %}
<!-- <div class="container">
    <div class="row">
        <div class="col-md-4 mb-4">
        <div class="embed-responsive embed-responsive-4by3" style="height: 80vh;">
            <video class="embed-responsive-item" controls>
                <source src="{{path}}" type="video/mp4">
            </video>
        </div>
        <h4>{{video_data["title"]}}</h4>
        </div>
    </div>
</div> -->
<div class="container my-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="embed-responsive embed-responsive-4by3 mb-3" style="height: 80vh;">
                <video class="embed-responsive-item" controls>
                    <source src="{{ url_for('api.api_get_video', videoid=video_data.videoid) }}" type="video/mp4">
                </video>
            </div>
            <h4 class="text-center">{{ video_data.title }}</h4>
            {% if not video_data.uploaded %}
            <div class="d-grid gap-2 col-6 mx-auto">
                <a href="{{ url_for('api.api_upload_video', video_id=video_data.videoid) }}"
                    class="btn btn-primary">UploadToYT</a>
                <a href="{{ url_for('view.update_video', video_id=video_data.videoid) }}" class="btn btn-warning">Edit
                </a>
                <a href="{{ url_for('api.api_delete_video', video_id=video_data.videoid) }}"
                    class="btn btn-danger">Delete</a>
            </div>
            {% else %}
            <div class="d-grid gap-2 col-6 mx-auto">
                <td><a href="https://youtube.com/video/{{ video_data.ytvideolink }}" class="btn btn-info">WatchOnYT</a>
                </td>
                <a href="{{ url_for('view.update_video', video_id=video_data.videoid) }}"
                    class="btn btn-warning">Edit</a>
                <a href="{{ url_for('api.api_delete_video', video_id=video_data.videoid) }}"
                    class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

templates/videos.html
{% extends "layout.html" %}
{% if error %}
<div class="alert alert-danger">{{ error }}</div>
{% endif %}

{% if success %}
<div class="alert alert-success">{{ success }}</div>
{% endif %}

{% block content %}
<div class="container mt-2">
    <h1>Video List</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Play Video</th>
                <th>Title</th>
                <th>Description</th>
                <th>Keywords</th>
                <th>Privacy Status</th>
                <th>Timestamp</th>
                <th>YouTube</th>
            </tr>
        </thead>
        <tbody id="videoList">

            {% for video in video_data %}
            <tr>
                <td><a href="/video/{{ video.videoid }}" class="btn btn-secondary">{{ video.file }}</a></td>
                <td>{{ video.title }}</td>
                <td>{{ video.description }}</td>
                <td>{{ video.keywords }}</td>
                <td>{{ video.privacyStatus }}</td>
                <td>{{ video.timestamp }}</td>

                {% if not video.uploaded %}
                <td><a href="{{ url_for('api.api_upload_video', video_id=video.videoid) }}"
                        class="btn btn-primary">UploadToYT</a>
                    <!-- {{video.ytvideolink}} -->
                </td>
                {% else %}
                <td>
                    <a href="https://youtube.com/video/{{video.ytvideolink}}" class="btn btn-info">WatchOnYT</a>
                    <!-- {{video.ytvideolink}} -->
                </td>
                <script>
                    console.log("{{video.ytvideolink}}");
                </script>
                {% endif %}
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>


{% endblock %}